apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring  # 可以換成你的 namespace
data:
  config.yaml: |
    receivers:
      filelog/blog:
        include: [/Users/linjiaxian/Desktop/logCollection/blogLogCollection/*.log]  # 讀取 blog 服務的日誌
        start_at: beginning
        attributes:
          loki:
            labels:
              service: "blog"
              env: "production"

      filelog/user:
        include: [/Users/linjiaxian/Desktop/logCollection/UserLogCollection/*.log]  # 讀取 user 服務的日誌
        start_at: beginning
        attributes:
          loki:
            labels:
              service: "user"
              env: "production"

      filelog/gateway:
        include: [/Users/linjiaxian/Desktop/logCollection/GateWayLogCollection/*.log]  # 讀取 gateway 服務的日誌
        start_at: beginning
        attributes:
          loki:
            labels:
              service: "gateway"
              env: "production"

    exporters:
      loki:
        endpoint: http://loki:3100/loki/api/v1/push

    service:
      pipelines:
        logs/blog:
          receivers: [filelog/blog]
          exporters: [loki]

        logs/user:
          receivers: [filelog/user]
          exporters: [loki]

        logs/gateway:
          receivers: [filelog/gateway]
          exporters: [loki]